spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: james
    password: jms990501
  thymeleaf:
    prefix: classpath:templates/pages/
    suffix: .html
    cache: false
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
  devtools:
    restart:
      enabled: true
    liveload:
      enabled: true
logging:
  level:
    root: info
    web: debug
security:
  basic:
    enabled: true