spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-blog-project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 0501
  devtools:
    restart:
      enabled: true
    liveload:
      enabled: true
logging:
  level:
    root: info
    web: debug
security:
  basic:
    enabled: true